## WIP
name: Devel_workflow

on:
  workflow_dispatch:

jobs:
  integ-oidc:
    permissions:
      contents: read
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        os: [[self-hosted, linux-fargate], [self-hosted, windows-fargate], windows-latest, ubuntu-latest, macos-latest]
        node: [14, 16, 18]
    name: Run OIDC integ tests
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
      - name: Integ test for OIDC
        uses: ./
        with:
          aws-region: us-west-2
          role-to-assume: ${{ secrets.SECRETS_OIDC_AWS_ROLE_TO_ASSUME }}
          role-duration-seconds: 900
          role-session-name: IntegOidcAssumeRole
          role-external-id: ${{ secrets.SECRETS_OIDC_AWS_ROLE_EXTERNAL_ID }}
  integ-access-keys:
    strategy:
      fail-fast: false
      matrix:
        os: [[self-hosted, linux-fargate], [self-hosted, windows-fargate], windows-latest, ubuntu-latest, macos-latest]
        node: [14, 16, 18]
    name: Run access key integ tests
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
      - name: Integ test for access keys
        uses: ./
        with:
          aws-region: us-west-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.SECRETS_AWS_ROLE_TO_ASSUME }}
          role-session-name: IntegAccessKeysAssumeRole
          role-external-id: ${{ secrets.SECRETS_AWS_ROLE_EXTERNAL_ID }}
  integ-iam-user:
    strategy:
      fail-fast: false
      matrix:
        os: [[self-hosted, linux-fargate], [self-hosted, windows-fargate], windows-latest, ubuntu-latest, macos-latest]
        node: [14, 16, 18]
    name: Run IAM User integ tests
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
      - name: Integ test for IAM user
        uses: ./
        with:
          aws-region: us-west-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  lint:
    name: Ensure code standards
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: "Checkout repostiory"
        uses: actions/checkout@v3
      - name: "Setup node"
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: "Install dependencies"
        uses: bahmutov/npm-install@v1
      - name: "Lint code"
        run: npm run lint --if-present
  # unit-test:
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       os: [windows-latest, ubuntu-latest, macos-latest]
  #       node: [14, 16, 18]
    # name: Run unit tests
    # runs-on: ${{ matrix.os }}
    # timeout-minutes: 5
    # steps:
    #   - name: "Checkout repository"
    #     uses: actions/checkout@v3
    #   - name: "Setup node"
    #     uses: actions/setup-node@v3
    #     with:
    #       node-version: ${{ matrix.node }}
    #   - name: "Install dependencies"
    #     uses: bahmutov/npm-install@v1
    #   - name: "Run tests"
    #     run: npm run test --if-present
