on:
  push:
    branches:
      - integ-tests

name: Integration Test

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Print current build ID
      run: |
        echo Integration test run: githubactionsconfigureawscr-hAMhr2qzHnWH:8741521a-e37b-4579-85b3-1a2f093819dd

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@18a20dfee9cc631f063c8b382c11c9120015b21d
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Test environment is configured with AWS credentials
      run: |
        aws sts get-caller-identity > /dev/null
